/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matrices.calculadora;

/**
 *
 * @author Juan Pablo Sanchez
 */
public class Diseño extends javax.swing.JPanel {

    /**
     * Creates new form Diseño
     */
    public Diseño() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SumaMatrices = new javax.swing.JButton();
        RestaMatrices = new javax.swing.JButton();
        MultiplicacionMatrices = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Resultado = new javax.swing.JButton();

        SumaMatrices.setText("Suma");
        SumaMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaMatricesActionPerformed(evt);
            }
        });

        RestaMatrices.setText("Resta");
        RestaMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaMatricesActionPerformed(evt);
            }
        });

        MultiplicacionMatrices.setText("Multiplicacion");

        jButton4.setText("AXB^-1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Resultado.setText("=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SumaMatrices)
                        .addGap(18, 18, 18)
                        .addComponent(RestaMatrices)
                        .addGap(18, 18, 18)
                        .addComponent(MultiplicacionMatrices)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Resultado)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SumaMatrices)
                    .addComponent(RestaMatrices)
                    .addComponent(MultiplicacionMatrices)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(Resultado)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SumaMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaMatricesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumaMatricesActionPerformed

    private void RestaMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaMatricesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaMatricesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MultiplicacionMatrices;
    private javax.swing.JButton RestaMatrices;
    private javax.swing.JButton Resultado;
    private javax.swing.JButton SumaMatrices;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
